# Site settings
title: "KeePassXC Password Manager"
baseurl: ""
url: "https://keepassxc.org"

# Build settings
markdown: kramdown
permalink: /:title

exclude:
  - .idea
  - Gemfile
  - package.json
  - package-lock.json
  - README.md

include:
  - .htaccess

sass:
  style: compressed
  implementation: sass-embedded
  sass_dir: _sass/
  load_paths:
    - assets/_sass/
    - node_modules/

copy_to_dest:
  - source: node_modules/@fortawesome/fontawesome-free/webfonts/.
    target: assets/webfonts/
  - source: node_modules/jquery/dist/.
    target: assets/js/

plugins:
  - jekyll-sitemap
